package claats

const indexTemplate = `<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta name="viewpoint" content="width=device-width, initial-scale=1">

	<title>{{.Title}}</title>

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

	{{if .GA}}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id={{.GA}}"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', '{{.GA}}');
	</script>
	{{end}}
</head>
<body>
	<header class="container mt-6 mb-6">
		<h1 class="title has-text-centered">{{.Title}}</h1>
	</header>
	<main class="container">
		{{range .Labs}}
    <section class="section">
      <h2 class="title">
        <a href="{{.Path}}">{{.Title}}</a>
      </h2>
      <h3 class="subtitle">{{.Summary}}</h3>
			<div>
				<p class="is-size-7 has-text-dark">
					Last updated:
					<span class="has-text-weight-bold">{{.Updated.Format "2006-01-02"}}</span>
					, Duration:
					<span class="has-text-weight-bold">{{.Duration}}</span>
					minutes
				</p>
			</div>
      <div class="mt-4">
				{{range .Tags}}
        <span class="tag is-info is-light">{{.}}</span>
				{{end}}
      </div>
    </section>
		{{end}}
	</main>
	<footer class="container mt-6">
		<p class="is-size-7 has-text-centered">
      Generated by <a href="https://github.com/ShawnLabo/claats" target="_blank">claats</a>.
    </p>
	</footer>
</body>
</html>
`
